# GitHub Sponsors
github: mibx-69

# Buy Me a Coffee
buy_me_a_coffee: 

# Ko-fi
ko_fi: 

# Patreon
patreon: 

# Open Collective
open_collective: 

# LiberaPay
liberapay: 

# Polar
polar: 

# Thanks.dev
thanks_dev: 

# Community Bridge
community_bridge: 

# Tidelift
tidelift: 

# Custom funding links (up to 4)
custom:
  - "https://www.moinulislam.pro"
  - "https://universesraw.com"
